# Exported from Render on 2026-04-21T15:40:53Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: clientes-app
      runtime: docker
      repo: https://github.com/racielfg01/clientes-app
      plan: free
      envVars:
      - key: REACT_APP_API_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_USER
        sync: false
      region: oregon
      dockerContext: .
      dockerfilePath: ./Dockerfile
      autoDeployTrigger: commit
